hello_django/urls.py
from django.contrib import admin
from django.urls import path
from . import views, testdb, form
from BookModel import views as book_views
from CookieModel import views as cookie_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello/", views.hello, name="hello"),
    path("", views.index, name="index"),
    path("show_img/", views.show_img, name="show_img"),
    path("test_add/", testdb.test_add, name="test_add"),
    path("test_get/", testdb.test_get, name="test_get"),
    path("test_update/", testdb.test_update, name="test_update"),
    path("test_del/", testdb.test_del, name="test_del"),

    path("search_form/", form.search_form, name="search_form"),
    path("search/", form.search, name="search"),
    path("post_form/", form.post_form, name="post_form"),

    path("add_book/", book_views.add_book, name="add_book"),
    path("add_book2author/", book_views.add_b2a, name="add_b2a"),
    path("use_set/", book_views.association_set, name="association_set"),
    path("find1/", book_views.one2many_find, name="one2many_find"),
    path("find2/", book_views.one2one_find, name="one2one_find"),
    path("find3/", book_views.many2many_find, name="many2many_find"),
    path("find4/", book_views.cross_table_find),

    path("use_aggregate/", book_views.use_aggregate),
    path("use_annotate/", book_views.use_annotate),

    path("use_f/", book_views.use_f),
    path("use_q/", book_views.use_q),

    path('add_emp/', book_views.add_emp),

    path('login/', cookie_views.login),
    path("index/", cookie_views.index),
    path('logout/', cookie_views.logout),
    path('order/', cookie_views.order),

    path('session_login/', cookie_views.s_login),
    path('s_index/', cookie_views.s_index),
    path('s_logout/', cookie_views.s_logout),

    path("login_class/", views.Login.as_view()),
]

BookModel/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    id = models.AutoField(primary_key=True)  # id 会自动创建,可以手动写入
    title = models.CharField(max_length=32)  # 书籍名称
    price = models.DecimalField(max_digits=5, decimal_places=2)  # 书籍价格
    publish = models.ForeignKey("Publish", on_delete=models.CASCADE)  # 出版社名称
    pub_date = models.DateField()  # 出版时间
    authors = models.ManyToManyField("Author")  # 会自动生成 book_authors 表


class Publish(models.Model):
    name = models.CharField(max_length=32)
    city = models.CharField(max_length=64)
    email = models.EmailField()


class Author(models.Model):
    name = models.CharField(max_length=32)
    age = models.SmallIntegerField()
    au_detail = models.OneToOneField("AuthorDetail", on_delete=models.CASCADE)


class AuthorDetail(models.Model):
    gender_choices = (
        (0, "女"),
        (1, "男"),
        (2, "保密"),
    )
    gender = models.SmallIntegerField(choices=gender_choices)
    tel = models.CharField(max_length=32)
    addr = models.CharField(max_length=64)
    birthday = models.DateField()


# ------------------------------------------------------------
class Emp(models.Model):
    name = models.CharField(max_length=32)
    age = models.IntegerField()
    salary = models.DecimalField(max_digits=8, decimal_places=2)
    dep = models.CharField(max_length=32)
    province = models.CharField(max_length=32)


class Emps(models.Model):
    name = models.CharField(max_length=32)
    age = models.IntegerField()
    salary = models.DecimalField(max_digits=8, decimal_places=2)
    dep = models.ForeignKey("Dep", on_delete=models.CASCADE)
    province = models.CharField(max_length=32)


class Dep(models.Model):
    title = models.CharField(max_length=32)

templates/add_emp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add EMP</title>
</head>
<body>

<h3>添加员工</h3>

<!-- 法1 自己写
<form action="" method="post">
    <p>姓名：<input type="text" name="name"></p>
    <p>年龄：<input type="text" name="age"></p>
    <p>工资：<input type="text" name="salary"></p>
    <input type="submit">
</form>
-->

<!-- 法2 通过form对象的as_p方法实现 -->
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{#法3 手动获取form对象的字段#}
{#<form action="" method="post" novalidate>#}
{#    {% csrf_token %}#}
{#    <div>#}
{#        <label for="id_{{ form.name.name }}">姓名</label>#}
{#        {{ form.name }} <span>{{ form.name.errors.0 }}</span>#}
{#    </div>#}
{#    <div>#}
{#        <label for="id_{{ form.age.name }}">年龄</label>#}
{#        {{ form.age }} <span>{{ form.age.errors.0 }}</span>#}
{#    </div>#}
{#    <div>#}
{#        <label for="id_salary">工资</label>#}
{#        {{ form.salary }} <span>{{ form.salary.errors.0 }}</span>#}
{#    </div>#}
{#    <input type="submit">#}
{#</form>#}


{#4、用for循环展示所有字段#}
{#<form action="" method="post" novalidate>#}
{#    {% csrf_token %}#}
{#    {% for field in form %}#}
{#        <div>#}
{#            <label for="id_{{ field.name }}">{{ field.label }}</label>#}
{#            {{ field }} <span>{{ field.errors.0 }}</span>#}
{#        </div>#}
{#    {% endfor %}#}
{#    <input type="submit">#}
{#</form>#}

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="/static/plugins/bootstrap-5.3.3-dist/css/bootstrap.css">
<head>
    <meta charset="UTF-8">
    <title>show IMG</title>
</head>
<body>
<h1>{{name}}</h1>
    {% block mainbody %}
    <p>  original text </p>
    {% endblock %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% load my_tags %}

<h1>{{ replace_text }}</h1>
<p>{{ replace_list }}</p>
<ul>
    <li>{{ replace_list.0 }}</li>
    <li>{{ replace_list.1 }}</li>
    <li>{{ replace_list.2 }}</li>
</ul>
<p>{{ replace_list | length }}</p>

<p>Time: {{ time }} </p>
<p> Date: {{ time | date:"Y-m-d" }} </p>

{{ safe_str }}<br>
{{ safe_str | safe }}

<p>if-else (Whether pass or not?) </p>
{% if if_else_num > 90 and if_else_num <= 100 %}
<h3>Excellent!</h3>
{% elif if_else_num > 60 and if_else_num <= 90 %}
<h3>Good!</h3>
{% else %}
<h3>SO BAD!</h3>
{% endif %}

<p>for (use 'replace_list') </p>
<ul>
{% for li_txt in replace_list reversed %}
    <li>{{ li_txt }}</li>
    <p>forloop.counter: {{ forloop.counter }}</p>
    <p>forloop.counter0: {{ forloop.counter0 }}</p>
    <p>forloop.revcounter: {{ forloop.revcounter }}</p>
    <p>forloop.revcounter0: {{ forloop.revcounter0 }}</p>
    <p>forloop.first: {{ forloop.first }}</p>
    <p>forloop.last: {{ forloop.last }}</p>
    <hr>
{% endfor %}
</ul>

<p> Custom filter : </p>
{{ 11 | my_filter:22 }}

<p> Custom tag : </p>
{% my_simple_tag 11 22 33 %}

<p>from django.utils.safestring import mark_safe: </p>
{% my_html "zzz" "xxx" %}
</body>
</html>

templates/index_cookie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index Cookie Page</title>
</head>
<body>
<h2>Cookie index 页面...</h2>
<a href="/logout/">注销</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login (COOKIES) Page</title>
</head>
<body>
<h3>用户登录</h3>
<form action="" method="post">
    {% csrf_token %}
    <label>
        用户名：
        <input type="text" name="username">
    </label>
    <label>
        密码：
        <input type="password" name="pwd">
    </label>
    <input type="submit">
</form>
</body>
</html>

templates/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Page</title>
</head>
<body>
<h2>order 页面。。。</h2>
<a href="/logout/">注销</a>
</body>
</html>

templates/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>post form</title>
</head>
<body>
    <form action="/post_form/" method="post">
        {% csrf_token %}  <!-- POST 必须要有的tag -->
        <input type="text" name="q">
        <input type="submit" value="提交">
    </form>
    <p>{{ rlt }}</p>  <!-- POST成功后显示 -->
</body>
</html>

templates/s_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Session Page</title>
</head>
<body>
<h2>session_index 页面。。。{{ request.session.user1 }}</h2>
<a href="/s_logout/">注销</a>
</body>
</html>

templates/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>search form</title>
</head>
<body>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="搜索">
    </form>
</body>
</html>

templates/show_img.html
{%extends "base.html" %}

{% load static %}

{% block mainbody %}
<p>extended FILE 'base.html'</p>
<img src="{% static 'images/profile.jpg' %}" alt=profile-img">
{% endblock %}